packages:
  - packages/*
  - libs/*
catalog:
  "@types/node": ^20
  "@types/react": ^19
  "@types/react-dom": ^19
  eslint: ^8
  eslint-config-next: 15.0.4
  next: 15.0.4
  postcss: ^8
  react: ^19.0.0
  react-dom: ^19.0.0
  tailwindcss: ^3.4.1
  typescript: ^5

catalogs:
  next-canary:
    next: 15.0.4-canary.45
    react: 19.0.0-rc.1
    react-dom: 19.0.0-rc.1
  next-stable:
    next: 15.0.4
    react: 19.0.0-rc.1
    react-dom: 19.0.0-rc.1